version: '3.8'

services:
  sistemalivraria:
    build: .
    container_name: sistemalivraria
    ports:
      - "5000:5000"
    volumes:
      - .:/sistemalivraria
    environment:
      - FLASK_ENV=development
    command: python /sistemalivraria/app.py
    depends_on:
      db:
        condition: service_healthy 

  db:
    image: mysql:8.0
    container_name: mysql_livraria
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 27052005
      MYSQL_DATABASE: livraria
    ports:
      - "3310:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    #verificação sql 
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p27052005"]
      interval: 5s
      timeout: 10s
      retries: 5
      start_period: 20s

volumes:
  mysql_data: