services:
  sistemalivraria:
    build: .
    container_name: sistemalivraria
    ports:
      - "5000:5000"
    volumes:
      - .:/sistemalivraria
    environment:
      - FLASK_ENV=development
    command: python /sistemalivraria/app.py
    depends_on:
      - db

  db:
    image: mysql:8.0
    container_name: mysql_livraria
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 27052005
      MYSQL_DATABASE: livraria
    ports:
      - "3310:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
